clear all;
C = imread("Trees.jpeg");
figure(1);
imshow(C);
D = C;
D(:, :, 2) = 0;
D(:, :, 3) = 0;
imwrite(D, "TreesRed.jpeg");
figure(2);
imshow(D);
E = C;
E(:, :, 1) = 0;
E(:, :, 3) = 0;
imwrite(E, "TreesGreen.jpeg");
figure(3);
imshow(E);
F = C;
F(:, :, 1) = 0;
F(:, :, 2) = 0;
imwrite(F, "TreesBlue.jpeg");
figure(4);
imshow(F);
